spring:
  application:
    name: "banking-cancel-debit"

server:
  port: 8080
  servlet:
    context-path: /banking-cancel-debit

aws:
  accessKey: ${AWS_ACCESS_KEY:test}
  secretKey: ${AWS_SECRET_KEY:test}
  awsEndpoint: ${AWS_ENDPOINT:http://localhost:4566}
  sqs:
    debitCancelQueueName: ${SQS_DEBIT_CANCEL_QUEUE_NAME:cancellation-queue}