openapi: 3.0.1
info:
  title: Debit Cancellation API
  version: 1.0.0
  description: API para cancelamento de débitos
paths:
  /debit/cancel:
    post:
      summary: Cancelar débito
      operationId: cancelDebit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CancelDebitRequest'
      responses:
        '200':
          description: Débito cancelado com sucesso
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '500':
          description: Erro interno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
components:
  schemas:
    CancelDebitRequest:
      type: object
      properties:
        debitId:
          type: string
          example: "debitId-2313"
        reason:
          type: string
          example: "Duplicated transaction"
        requestedBy:
          type: string
          example: "user-123"
      required:
        - debitId
        - reason
        - requestedBy
    ApiErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          example: "2025-06-08T14:23:00Z"
        status:
          type: integer
          example: 400
        error:
          type: string
          example: "Bad Request"
        message:
          type: string
          example: "Missing required field: debitId"
